### ISSUE TITLE
Citing Use?

### ISSUE THREAD

**Issue by dshen109** [PrincetonUniversity/PGscen#2]
Hello, I'm currently writing a paper that will use PGSCen wind data generated for the RTS-GMLC system. Is there a preferred way I should cite the PGScen project?

**Comment by xy3134** [comment]
Hi,

We recently posted a paper on arXiv (https://arxiv.org/abs/2209.13497). Please use that paper as a reference for PGscen.

Thanks,
Xinshuo Yang
